# Meta data
openapi: '3.0.3'
info:
  version: 'v2.3'
  title: 'Freeday API'
servers:
  - url: 'https://beta.freeday.coddity.com'

# API routes
paths:
  # Authentication
  /api/auth:
    $ref: './api/paths/auth/auth.yaml'
  /api/auth/welcome:
    $ref: './api/paths/auth/auth-welcome.yaml'
  # Users
  /api/users:
    $ref: './api/paths/users/users.yaml'
  /api/users/{userId}:
    $ref: './api/paths/users/users-id.yaml'
  # Slack
  /api/slack/auth:
    $ref: './api/paths/slack/slack-auth.yaml'
  /api/slack/users:
    $ref: './api/paths/slack/slack-users.yaml'
  /api/slack/users/{slackUserId}:
    $ref: './api/paths/slack/slack-users-id.yaml'
  /api/slack/channels:
    $ref: './api/paths/slack/slack-channels.yaml'
  /api/slack/channels/{slackChannelId}:
    $ref: './api/paths/slack/slack-channels-id.yaml'
  /api/slack/events:
    $ref: './api/paths/slack/slack-events.yaml'
  # Daysoff
  /api/daysoff:
    $ref: './api/paths/daysoff/daysoff.yaml'
  /api/daysoff/{dayoffId}:
    $ref: './api/paths/daysoff/daysoff-id.yaml'
  /api/daysoff/{dayoffId}/conflicts:
    $ref: './api/paths/daysoff/daysoff-id-conflicts.yaml'
  /api/daysoff/{dayoffId}/confirm:
    $ref: './api/paths/daysoff/daysoff-id-confirm.yaml'
  /api/daysoff/{dayoffId}/cancel:
    $ref: './api/paths/daysoff/daysoff-id-cancel.yaml'
  /api/daysoff/{dayoffId}/reset:
    $ref: './api/paths/daysoff/daysoff-id-reset.yaml'
  # Dayoff types
  /api/daysoff/types:
    $ref: './api/paths/dayoffTypes/daysoff-types.yaml'
  /api/daysoff/types/{dayoffTypeId}:
    $ref: './api/paths/dayoffTypes/daysoff-types-id.yaml'
  # Configuration
  /api/configuration:
    $ref: './api/paths/configuration/configuration.yaml'
  /api/configuration/public:
    $ref: './api/paths/configuration/configuration-public.yaml'
  # Jobs
  /api/jobs/{jobName}:
    $ref: './api/paths/jobs/jobs-name.yaml'
  # Misc
  /api/ping:
    $ref: './api/paths/misc/ping.yaml'

# Components
components:
  # Security
  securitySchemes:
    BearerToken:
      type: 'http'
      scheme: 'bearer'
      description: 'Authentication bearer token'

security:
  - BearerToken: []
