kind: pipeline
type: docker
name: freeday-api

trigger:
  branch:
  - dev
  event:
  - push
  - pull_request

services:
- name: mongo
  image: mongo:latest

steps:
- name: install
  image: node:16-alpine
  pull: if-not-exists
  commands:
  - npm ci
- name: lint
  image: node:16-alpine
  pull: if-not-exists
  commands:
  - npm run lint
  depends_on:
  - install
- name: test
  image: node:16-alpine
  pull: if-not-exists
  commands:
  - cp .env.ci .env
  - mkdir -p /var/log/freeday
  - npm run test
  depends_on:
  - install
- name: sonarqube
  image: pitininja/drone-sonar-plugin:latest
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  depends_on:
  - install
  when:
    branch:
    - dev
    event:
    - push

---
kind: pipeline
type: docker
name: freeday-docker

trigger:
  event:
  - tag

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone https://github.com/freeday-app/freeday-docker.git .
- name: docker  
  image: plugins/docker
  settings:
    repo: freedayapp/freeday
    tags:
    - ${DRONE_TAG}
    - latest
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password
