kind: pipeline
type: docker
name: freeday-api

trigger:
  branch:
  - dev

services:
- name: mongo
  image: mongo:latest

steps:
- name: dependencies
  image: node:14-alpine
  pull: if-not-exists
  commands:
  - npm i
- name: lint
  image: node:14-alpine
  pull: if-not-exists
  commands:
  - npm run lint
  depends_on:
  - dependencies
- name: test
  image: node:14-alpine
  pull: if-not-exists
  commands:
  - cp .env.ci .env
  - mkdir -p /var/log/freeday
  - npm run test
  depends_on:
  - dependencies
- name: sonarqube
  image: pitininja/drone-sonar-plugin:latest
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
  depends_on:
  - dependencies

---
kind: pipeline
type: docker
name: freeday-docker

trigger:
  event:
  - tag

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone https://github.com/freeday-app/freeday-docker.git .
- name: docker  
  image: plugins/docker
  settings:
    repo: freedayapp/freeday
    tags:
    - ${DRONE_TAG}
    - latest
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password
